// CarineStudy — ordem na grade = `ordem`. `provaAtual` = destaque visual (liberada). `emBreve` = futuro, sem pagamento/código.
const MATERIAS = {
  felinos: {
    id: "felinos",
    ordem: 10,
    apenasMemoria: true,
    desativado: true,
    provaConcluida: true,
    nome: "Eletiva II — Felinos",
    icone: "🐱",
    descricao:
      "Prova dessa eletiva já passou. Card só para lembrar a conquista — não abre estudo no app.",
    corPrimaria: "#7c3aed",
    corSecundaria: "#f59e0b",
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  clinicaPeqAnimais: {
    id: "clinicaPeqAnimais",
    ordem: 20,
    provaAtual: true,
    nome: "Clínica Médica e Terapêutica — PDF",
    icone: "🩺",
    descricao:
      "Só o que está no material da prova: semiótica, prescrição, cardio e convulsões. Força, Carine — João na torcida 💜",
    corPrimaria: "#0d9488",
    corSecundaria: "#f472b6",
    cramFlashN: 18,
    cramMcN: 12,

    flashcards: [
      { id: "cp-fc1", frente: "Na proporção típica do exame clínico, quanto pesa a anamnese?", verso: "Cerca de 50% da avaliação — o histórico do animal é a base de tudo.", topico: "exame-clinico" },
      { id: "cp-fc2", frente: "E o exame físico, em porcentagem aproximada?", verso: "~35%. Resenha ~0%; exames complementares ~15%.", topico: "exame-clinico" },
      { id: "cp-fc3", frente: "O que é inspeção na semiótica?", verso: "Observação visual do aspecto interno e externo: postura, locomoção, condição corporal, pelame.", topico: "semiotica" },
      { id: "cp-fc4", frente: "Palpação: consistência mole, firme, dura, pastosa, flutuante e crepitante indicam o quê?", verso: "Mole: normal; firme: fígado/músculo; dura: osso/tumor; pastosa: Godet +; flutuante: líquido; crepitante: ar/gás.", topico: "semiotica" },
      { id: "cp-fc5", frente: "Na avaliação de linfonodos, o que observar?", verso: "Consistência, mobilidade (aderido ou não) e temperatura.", topico: "semiotica" },
      { id: "cp-fc6", frente: "Quais são os parâmetros vitais clássicos no exame físico?", verso: "Temperatura, mucosas, TPC, FC, FR, pulso arterial e pressão arterial.", topico: "exame-clinico" },
      { id: "cp-fc7", frente: "Diferença entre diagnóstico clínico e diferencial?", verso: "Clínico: definido na clínica pelo exame. Diferencial: lista de causas possíveis pelos sinais (ex.: vômito/diarreia — ancilostomose, toxocara, cinomose).", topico: "diagnostico-prognostico" },
      { id: "cp-fc8", frente: "Tipos de prognóstico mencionados no material?", verso: "Favorável; reservado ou desfavorável — previsão de resposta ao tratamento.", topico: "diagnostico-prognostico" },
      { id: "cp-fc9", frente: "Melena vs hematoquezia — em uma frase cada.", verso: "Melena: fezes enegrecidas (sangue digerido). Hematoquezia: sangue vivo nas fezes.", topico: "termos-tecnicos" },
      { id: "cp-fc10", frente: "Ortopneia é o quê?", verso: "Respiração com pescoço estendido — alívio postural da dificuldade respiratória.", topico: "termos-tecnicos" },
      { id: "cp-fc11", frente: "Azotemia — definição.", verso: "Aumento de ureia e creatinina séricas.", topico: "termos-tecnicos" },
      { id: "cp-fc12", frente: "Dose vs dosagem na prescrição?", verso: "Dose: quantidade por administração. Dosagem: dose + frequência + duração do tratamento.", topico: "prescricao" },
      { id: "cp-fc13", frente: "Intervalo entre gotas de colírios (material)?", verso: "Cerca de 5 minutos entre colírios diferentes.", topico: "prescricao" },
      { id: "cp-fc14", frente: "Receita A (amarela) — o que controla?", verso: "Listas A1/A2 entorpecentes e A3 psicróticos; alta dependência; validade 30 dias; numeração ANVISA; antibiótico associado até 10 dias no modelo citado.", topico: "receituario" },
      { id: "cp-fc15", frente: "Receita B (azul) vs C (branca) — ideia geral.", verso: "B: B1/B2, menos restritiva que A. C: mais flexível (antibióticos humanos controlados, ansiolíticos etc.), 2 vias.", topico: "receituario" },
      { id: "cp-fc16", frente: "Portaria 344/98 — papel das receitas A, B e C.", verso: "Regulam substâncias com potencial de abuso, dependência ou risco sanitário.", topico: "receituario" },
      { id: "cp-fc17", frente: "SIPEAGRO — exemplo de uso na aula?", verso: "Medicamentos veterinários de controle especial — ex.: cetamina e xilazina com receita SIPEAGRO.", topico: "receituario" },
      { id: "cp-fc18", frente: "MAPA na cadeia de medicamentos vet?", verso: "Fiscalização e liberação de produtos de uso veterinário.", topico: "receituario" },
      { id: "cp-fc19", frente: "Ivermectina — alerta do material para qual raça?", verso: "Contra-indicação/cuidado em cães pastores (sensibilidade MDR1).", topico: "prescricao" },
      { id: "cp-fc20", frente: "Cardiomiopatia hipertrófica — quem mais sofre?", verso: "Felinos — principal cardiomiopatia nos gatos; hipertrofia do septo interventricular reduz lúmen.", topico: "cardio-peq" },
      { id: "cp-fc21", frente: "Edema pulmonar cardiogênico — qual lado?", verso: "Insuficiência cardíaca esquerda — cardiogênico é sempre lado esquerdo no raciocínio do material.", topico: "cardio-peq" },
      { id: "cp-fc22", frente: "Líquido inflamatório no parênquima pulmonar vs não inflamatório?", verso: "Inflamatório: pneumonia. Não inflamatório: edema pulmonar.", topico: "cardio-peq" },
      { id: "cp-fc23", frente: "Tosse cardíaca vs respiratória (material).", verso: "Cardíaca: coração aumentado desloca dorsalmente traqueia — tosse seca, improdutiva, baixa intensidade. Respiratória: alta intensidade e forte.", topico: "cardio-peq" },
      { id: "cp-fc24", frente: "Graduação de sopros I a III (resumo).", verso: "I: brando. II: brando mas fácil de ouvir. III: moderado. (IV–VI: mais intenso + frêmito.)", topico: "cardio-peq" },
      { id: "cp-fc25", frente: "Endocardite degenerativa mitral — prevalência em cães?", verso: "Principal causa de doença cardíaca em cães; ~60% só mitral, 30% mitral+tricúspide, 10% só tricúspide.", topico: "dmvd" },
      { id: "cp-fc26", frente: "Tratamento farmacológico citado para DMVD / ICC (esqueleto).", verso: "IECA (benazepril/enalapril), furosemida, espironolactona, dieta hipossódica, repouso; pimobendana conforme estágio (inodilatador).", topico: "dmvd" },
      { id: "cp-fc27", frente: "Doses máximas de furosemida citadas (cão/gato).", verso: "Gato até ~4 mg/kg; cão até ~8 mg/kg (material de aula — conferir protocolo clínico atual).", topico: "dmvd" },
      { id: "cp-fc28", frente: "Órgãos-alvo da hipertensão arterial sistêmica.", verso: "Olhos (cegueira, glaucoma, hemorragias, descolamento de retina), rins, coração (hipertrofia concêntrica), SNC (AVC, convulsões).", topico: "hipertensao" },
      { id: "cp-fc29", frente: "ATE em gato — plano terapêutico citado.", verso: "Estabilizar, analgesia (butorfanol), heparina, AAS e repouso; prognóstico reservado.", topico: "ate-gato" },
      { id: "cp-fc30", frente: "Pericardiocentese — espaço intercostal citado.", verso: "7º espaço intercostal (material).", topico: "pericardio" },
      { id: "cp-fc31", frente: "Dispneia inspiratória vs expiratória vs mista.", verso: "Inspiratória: vias aéreas superiores. Expiratória: pulmões/brônquios. Mista: TRS + TRI comprometidos.", topico: "respiratorio" },
      { id: "cp-fc32", frente: "Fases da convulsão: pródromo, aura, icto, pós-icto.", verso: "Pródromo: comportamento, EEG normal. Aura: sinais estereotipados, EEG alterado. Icto: crise. Pós-icto: sedação/sede/comportamento alterado.", topico: "epilepsia" },
      { id: "cp-fc33", frente: "Emergência convulsiva: midazolam vs diazepam (material).", verso: "Midazolam: 1ª opção — hidrossolúvel, IN/IV/IM, ~0,3 mg/kg. Diazepam: 2ª — IV 0,5 mg/kg ou retal 2 mg/kg; hepatotoxicidade relativa.", topico: "epilepsia" },
      { id: "cp-fc34", frente: "Tratamento crônico de eleição para epilepsia?", verso: "Fenobarbital — monitorar níveis séricos (faixa terapêutica ~20–35 µg/mL) e bioquímica a cada 6 meses.", topico: "epilepsia" },
      { id: "cp-fc35", frente: "Brometo de potássio — cuidado em cardiopatas e uso em felinos.", verso: "Forma potássica usada em ICC; não usar em felinos (pode causar dificuldade respiratória).", topico: "epilepsia" },
      { id: "cp-fc36", frente: "Hipoglicemia vs hipocalcemia — pistas de paciente (material).", verso: "Filhote pequeno convulsionando: pensar hipoglicemia. Fêmea pós-parto convulsionando: hipocalcemia.", topico: "epilepsia" },
      { id: "cp-fc37", frente: "Etiologias de convulsão — mnemônico VITAMINAD (ideia).", verso: "Vascular, inflamatório/infeccioso/idiopático, trauma/tóxico, anomalias, metabólico, inflamatório, neoplasia/nutricional, anomalias, degeneração — esquema de classificação extracraniana/intracraniana.", topico: "epilepsia" },
    ],

    multiplaEscolha: [
      { id: "cp-mc1", pergunta: "Na estrutura do exame clínico, qual componente tem maior peso relativo (~50%)?", alternativas: [{ texto: "Resenha", correta: false }, { texto: "Anamnese", correta: true }, { texto: "Exame físico", correta: false }, { texto: "Exames complementares", correta: false }], topico: "exame-clinico", explicacao: "O histórico (anamnese) é a maior fatia — sem ele o físico fica 'cego'." },
      { id: "cp-mc2", pergunta: "Godet positivo na palpação sugere:", alternativas: [{ texto: "Osso exposto", correta: false }, { texto: "Consistência pastosa / flutuação compatível com líquido na cavidade", correta: true }, { texto: "Tecido ósseo duro", correta: false }, { texto: "Gás livre subcutâneo", correta: false }], topico: "semiotica", explicacao: "Pastoso/flutuante relaciona-se a líquido; Godet avalia deslocamento de fluido." },
      { id: "cp-mc3", pergunta: "Qual par não corresponde ao termo técnico?", alternativas: [{ texto: "Êmese — vômito", correta: false }, { texto: "Tenesmo — esforço para urinar sem resultado", correta: true }, { texto: "Dispneia — dificuldade respiratória", correta: false }, { texto: "Polaciúria — micções frequentes", correta: false }], topico: "termos-tecnicos", explicacao: "Tenesmo é esforço para defecar; disúria é dor ao urinar." },
      { id: "cp-mc4", pergunta: "Tratamento clínico envolve:", alternativas: [{ texto: "Apenas cirurgia", correta: false }, { texto: "Medicamentos e fluidoterapia", correta: true }, { texto: "Somente fitoterapia", correta: false }, { texto: "Jejum prolongado", correta: false }], topico: "diagnostico-prognostico", explicacao: "Tratamento clínico = fármacos + suporte (incluindo fluidos)." },
      { id: "cp-mc5", pergunta: "Prescrição para animal cardiopata deve ser:", alternativas: [{ texto: "Somente verbal", correta: false }, { texto: "Para manipulação, pois uso pode ser prolongado", correta: true }, { texto: "Sem assinatura", correta: false }, { texto: "Apenas digitada sem carimbo", correta: false }], topico: "prescricao", explicacao: "O material enfatiza receita para manipulação em cardiopatas." },
      { id: "cp-mc6", pergunta: "Receita A (amarela) é a mais restritiva porque inclui:", alternativas: [{ texto: "Somente vacinas", correta: false }, { texto: "Entorpecentes e psicotrópicos de alto potencial", correta: true }, { texto: "Shampoos antipulga", correta: false }, { texto: "Vitaminas", correta: false }], topico: "receituario", explicacao: "Listas A1, A2, A3 — controle máximo pela Portaria 344/98." },
      { id: "cp-mc7", pergunta: "Cetamina e xilazina (controle especial vet) exigem:", alternativas: [{ texto: "Receita branca simples", correta: false }, { texto: "Receita SIPEAGRO", correta: true }, { texto: "Somente nota fiscal", correta: false }, { texto: "Receita de padaria", correta: false }], topico: "receituario", explicacao: "SIPEAGRO para medicamentos controlados de uso veterinário específicos." },
      { id: "cp-mc8", pergunta: "Cardiomiopatia hipertrófica é mais prevalente em:", alternativas: [{ texto: "Cães de grande porte", correta: false }, { texto: "Felinos", correta: true }, { texto: "Aves", correta: false }, { texto: "Répteis", correta: false }], topico: "cardio-peq", explicacao: "CMH é a estrela (e o vilão) da cardiologia felina." },
      { id: "cp-mc9", pergunta: "Edema pulmonar cardiogênico está ligado a:", alternativas: [{ texto: "ICC direita isolada", correta: false }, { texto: "Insuficiência cardíaca esquerda", correta: true }, { texto: "Apenas pneumonia bacteriana", correta: false }, { texto: "Hipotireoidismo sem ICC", correta: false }], topico: "cardio-peq", explicacao: "Congestão pulmonar por aumento de pressão capilar esquerda." },
      { id: "cp-mc10", pergunta: "Sopro grau VI na escala do material:", alternativas: [{ texto: "Inaudível", correta: false }, { texto: "Muito alto, estetoscópio levemente afastado + frêmito", correta: true }, { texto: "Só com Doppler", correta: false }, { texto: "Normal fisiológico", correta: false }], topico: "cardio-peq", explicacao: "Grau VI é o extremo da escala de intensidade + frêmito precordial." },
      { id: "cp-mc11", pergunta: "Endocardite degenerativa mitral é mais comum em:", alternativas: [{ texto: "Gatos jovens", correta: false }, { texto: "Cães pequenos, machos, idosos (predisposição)", correta: true }, { texto: "Equinos", correta: false }, { texto: "Suínos", correta: false }], topico: "dmvd", explicacao: "DMVD — cães pequenos idosos, gênero macho, fator genético." },
      { id: "cp-mc12", pergunta: "Pimobendana no estágio B2 (material) atua como:", alternativas: [{ texto: "Antibiótico", correta: false }, { texto: "Inodilatador — aumenta contratilidade e ejeção", correta: true }, { texto: "Anticonvulsivante", correta: false }, { texto: "Antiemético", correta: false }], topico: "dmvd", explicacao: "Usada quando há progressão clínica/risco — inodilatador." },
      { id: "cp-mc13", pergunta: "Endocardite infecciosa — agentes citados:", alternativas: [{ texto: "Só vírus", correta: false }, { texto: "Streptococcus, Staphylococcus, E. coli", correta: true }, { texto: "Só fungos", correta: false }, { texto: "Helmintos", correta: false }], topico: "endocardite", explicacao: "Bactérias gram + e E. coli frequentes; vegetações valvares ao eco." },
      { id: "cp-mc14", pergunta: "Ecocardiograma na endocardite mostra vegetações descritas como:", alternativas: [{ texto: "Cálculo renal", correta: false }, { texto: "Aspecto em 'dedos de luva' / remodelamento valvar", correta: true }, { texto: "Derrame pericárdico seco", correta: false }, { texto: "Hidronefrose", correta: false }], topico: "endocardite", explicacao: "Vegetações e insuficiência secundária são marcas do quadro." },
      { id: "cp-mc15", pergunta: "Paralisia de membros pélvicos, dor, ausência de pulso femoral em gato com CMH sugere:", alternativas: [{ texto: "Otite", correta: false }, { texto: "Tromboembolismo aórtico (saddle thrombus)", correta: true }, { texto: "Luxação de quadril bilateral", correta: false }, { texto: "Gastroenterite", correta: false }], topico: "ate-gato", explicacao: "ATE secundária a CMH — emergência felina clássica." },
      { id: "cp-mc16", pergunta: "Derrame pericárdico com tamponamento — abordagem:", alternativas: [{ texto: "Ignorar se assintomático", correta: false }, { texto: "Pericardiocentese / retirada parcial do saco conforme caso", correta: true }, { texto: "Somente anti-inflamatório oral", correta: false }, { texto: "Banho e tosa", correta: false }], topico: "pericardio", explicacao: "Drenar o líquido alivia o tamponamento; exsudato séptico: ATB." },
      { id: "cp-mc17", pergunta: "Neoplasias cardíacas comuns em idosos (material):", alternativas: [{ texto: "Hemangiossarcoma atrial direito e linfossarcoma", correta: true }, { texto: "Somente papiloma cutâneo", correta: false }, { texto: "Cisto ovariano", correta: false }, { texto: "Tumor de glândula anal", correta: false }], topico: "pericardio", explicacao: "Podem causar derrame pericárdico e sinais de baixo débito." },
      { id: "cp-mc18", pergunta: "Convulsão é:", alternativas: [{ texto: "Sempre diagnóstico único 'epilepsia'", correta: false }, { texto: "Manifestação clínica — pode ter várias causas", correta: true }, { texto: "Sempre hipoglicemia", correta: false }, { texto: "Normal após banho", correta: false }], topico: "epilepsia", explicacao: "Convulsão é sinal, não doença única — investigar causa." },
      { id: "cp-mc19", pergunta: "Melhor opção de benzodiazepínico em emergência convulsiva (material):", alternativas: [{ texto: "Diazepam sempre em qualquer espécie sem restrição", correta: false }, { texto: "Midazolam — mais hidrossolúvel e versátil", correta: true }, { texto: "Clordiazepóxido oral", correta: false }, { texto: "Placebo", correta: false }], topico: "epilepsia", explicacao: "Midazolam 1ª linha; vias IV/IM/SC/IN conforme cenário." },
      { id: "cp-mc20", pergunta: "Fenobarbital crônico — monitoramento:", alternativas: [{ texto: "Nunca repetir exames", correta: false }, { texto: "Bioquímica hepática/renal periódica e níveis séricos", correta: true }, { texto: "Só contar convulsões", correta: false }, { texto: "Suspender se o animal comer ração", correta: false }], topico: "epilepsia", explicacao: "Hepatotoxicidade possível; faixa terapêutica ~20–35 µg/mL." },
      { id: "cp-mc21", pergunta: "Brometo de sódio vs potássio (ideia do material):", alternativas: [{ texto: "Sódio em hipoadrenocorticismo; potássio em ICC", correta: true }, { texto: "São intercambiáveis sem critério", correta: false }, { texto: "Só para felinos", correta: false }, { texto: "Contraindicados em qualquer cão", correta: false }], topico: "epilepsia", explicacao: "Escolha do sal conforme comorbidade — brometo não em felinos." },
      { id: "cp-mc22", pergunta: "Hipertensão sistêmica — causas citadas no material incluem:", alternativas: [{ texto: "Hipotireoidismo, hiperadrenocorticismo, diabetes", correta: true }, { texto: "Somente trauma craniano", correta: false }, { texto: "Somente verminose", correta: false }, { texto: "Exclusivamente alergia alimentar", correta: false }], topico: "hipertensao", explicacao: "SRAA e doenças endócrinas entram no jogo fisiopatológico." },
      { id: "cp-mc23", pergunta: "Ausculta mitral no cão — região típica:", alternativas: [{ texto: "Último espaço intercostal direito caudal", correta: false }, { texto: "Hemi-tórax esquerdo (EIC 4–5 esquerdo)", correta: true }, { texto: "Região lombar", correta: false }, { texto: "Mandíbula", correta: false }], topico: "cardio-peq", explicacao: "Foco mitral à esquerda; tricúspide mais à direita (4º EIC d)." },
      { id: "cp-mc24", pergunta: "Pneumonia vs edema pulmonar na lógica do conteúdo:", alternativas: [{ texto: "Ambos sempre sem febre", correta: false }, { texto: "Pneumonia: líquido inflamatório no parênquima; edema: não inflamatório", correta: true }, { texto: "São sinônimos", correta: false }, { texto: "Só radiografia de membros resolve", correta: false }], topico: "cardio-peq", explicacao: "Diferenciar etiologia guia antibiótico vs manejo de ICC." },
    ],

    dissertativas: [
      { id: "cp-d1", pergunta: "Liste os quatro blocos do exame clínico com os percentuais aproximados do material.", respostaEsperada: "Resenha ~0%; anamnese ~50%; exame físico ~35%; exames complementares ~15%.", topico: "exame-clinico" },
      { id: "cp-d2", pergunta: "Explique inspeção, percussão, palpação e auscultação em uma linha cada.", respostaEsperada: "Inspeção: observação visual global. Percussão: batidas para sons de cavidades. Palpação: tacto da consistência e conteúdos. Auscultação: estetoscópio em traqueia, pulmão, coração e TGI.", topico: "semiotica" },
      { id: "cp-d3", pergunta: "O que deve constar na prescrição médica veterinária (itens principais)?", respostaEsperada: "Cabeçalho (clínica, endereço, telefone); identificação do paciente (nome, espécie, idade, raça, sexo) e tutor; medicamento (nome, concentração, quantidade); tipo de uso; instruções (via, intervalo, duração). Caneta preta, sem rasura, assinatura e carimbo.", topico: "prescricao" },
      { id: "cp-d4", pergunta: "Compare receitas A, B e C quanto ao grau de restrição.", respostaEsperada: "A (amarela): mais restritiva — entorpecentes/psicróticos fortes. B (azul): intermediária. C (branca): mais flexível entre as controladas, 2 vias. Todas sob Portaria 344/98.", topico: "receituario" },
      { id: "cp-d5", pergunta: "Descreva ICC esquerda vs direita com sinais-chave.", respostaEsperada: "Esquerda: congestão pulmonar, edema pulmonar, dispneia, tosse cardíaca. Direita: congestão sistêmica, ascite, hepatomegalia, edema de membros pélvicos, efusão pleural.", topico: "cardio-peq" },
      { id: "cp-d6", pergunta: "Monte um plano terapêutico para DMVD estágio B2/C com fármacos do material.", respostaEsperada: "IECA (benazepril/enalapril), diurético de alça (furosemida), espironolactona se indicado, pimobendana conforme estágio, dieta hipossódica, repouso relativo, monitorar função renal e eletrólitos.", topico: "dmvd" },
      { id: "cp-d7", pergunta: "Como diferenciar tosse cardíaca de tosse respiratória?", respostaEsperada: "Cardíaca: coração aumentado comprime/desloca traqueia dorsalmente — tosse seca, improdutiva, fraca. Respiratória: intensa e produtiva/forte, ligada a vias/pulmão.", topico: "cardio-peq" },
      { id: "cp-d8", pergunta: "Emergência convulsiva: passos com midazolam e se refratário?", respostaEsperada: "Midazolam IV/IM/IN ~0,3 mg/kg até 2–3 doses/24h; se não cessar, considerar anestesia curta (propofol/cetamina) para proteger o cérebro; oxigenoterapia, resfriamento se hipertermia, tratar causa de base.", topico: "epilepsia" },
      { id: "cp-d9", pergunta: "Quando pensar em hipoglicemia e hipocalcemia como causa de convulsão?", respostaEsperada: "Filhote pequeno: hipoglicemia. Fêmea recentemente parida: eclâmpsia/hipocalcemia. Sempre glicemia e Ca no trabalho.", topico: "epilepsia" },
      { id: "cp-d10", pergunta: "Tratamento de ATE felina segundo o roteiro da aula.", respostaEsperada: "Estabilizar paciente; analgesia (butorfanol); anticoagulação (heparina); AAS; repouso absoluto; prognóstico reservado.", topico: "ate-gato" },
    ],

    casosClinicos: [
      {
        id: "cp-cc1",
        titulo: "Caso — Cão com sopro e tosse seca",
        topico: "dmvd",
        cenario:
          "Mel, pinscher 11 anos, 3 kg, tosse leve noturna, intolerância a exercícios, sopro holossistólico forte no 5º EIC esquerdo. Radiografia: veia pulmonar congestiva.",
        perguntas: [
          { texto: "Suspeita principal e por quê?", resposta: "Degeneração mixomatosa da valva mitral (DMVD) — cão pequeno idoso, sopro mitral, sinais de congestão pulmonar/tosse cardíaca.", tipo: "dissertativa" },
          { texto: "Três classes de fármacos do material + um não farmacológico.", resposta: "IECA (benazepril/enalapril), diurético (furosemida), inodilatador (pimobendana) conforme estágio; dieta hipossódica e repouso.", tipo: "dissertativa" },
          { texto: "Por que a tosse pode ser 'cardíaca' neste caso?", resposta: "Aumento atrial/esquerda desloca traqueia dorsalmente, irritando mucosa — tosse seca e improdutiva.", tipo: "dissertativa" },
        ],
      },
      {
        id: "cp-cc2",
        titulo: "Caso — Gato com dispneia e membros frios",
        topico: "ate-gato",
        cenario:
          "Nina, SRD 6 anos, cardiopata conhecida, de repente não usa membros pélvicos, vocaliza dor, pulso femoral ausente, mucosas pálidas.",
        perguntas: [
          { texto: "Diagnóstico provável?", resposta: "Tromboembolismo aórtico (saddle thrombus) secundário a CMH.", tipo: "dissertativa" },
          { texto: "Conduta imediata (material).", resposta: "Estabilizar, analgesia com butorfanol, heparina, AAS, repouso; explicar prognóstico reservado ao tutor.", tipo: "dissertativa" },
        ],
      },
      {
        id: "cp-cc3",
        titulo: "Caso — Prescrição incompleta",
        topico: "prescricao",
        cenario:
          "Estagiário redige receita só com nome do remédio e 'dar para o cão'. Tutor compra dose humana errada.",
        perguntas: [
          { texto: "O que faltou na prescrição?", resposta: "Identificação completa do paciente e tutor, concentração, quantidade, via, intervalo, duração, assinatura e carimbo; evitar abreviaturas.", tipo: "dissertativa" },
          { texto: "Por que cardiopatas precisam de manipulação?", resposta: "Tratamento prolongado — doses precisas e rastreabilidade do que foi prescrito.", tipo: "dissertativa" },
        ],
      },
      {
        id: "cp-cc4",
        titulo: "Caso — Convulsão em filhote",
        topico: "epilepsia",
        cenario:
          "Chihuahua 8 semanas, 600 g, em jejum prolongado após viagem, tremores e convulsão na chegada à clínica.",
        perguntas: [
          { texto: "Primeira hipótese metabólica?", resposta: "Hipoglicemia — filhote pequeno, jejum, estresse.", tipo: "dissertativa" },
          { texto: "Após estabilizar glicemia, qual benzodiazepínico de 1ª escolha se crise persistir?", resposta: "Midazolam (0,3 mg/kg) IV/IM/IN conforme disponibilidade.", tipo: "dissertativa" },
        ],
      },
      {
        id: "cp-cc5",
        titulo: "Caso — Endocardite",
        topico: "endocardite",
        cenario:
          "Pastor alemão 5 anos, febre, prostração, novo sopro, leucocitose com desvio à esquerda, hemocultura positiva.",
        perguntas: [
          { texto: "Diagnóstico e exame de imagem-chave?", resposta: "Endocardite bacteriana — ecocardiograma com vegetações valvares ('dedos de luva').", tipo: "dissertativa" },
          { texto: "Linha de tratamento.", resposta: "Antibioticoterapia prolongada guiada por hemocultura/antibiograma; suporte clínico; monitorar ICC.", tipo: "dissertativa" },
        ],
      },
      {
        id: "cp-cc6",
        titulo: "Caso — Derrame pericárdico",
        topico: "pericardio",
        cenario:
          "Dogue alemão 7 anos, abafamento cardíaco, pulso paradoxal, radiografia com silhueta globosa.",
        perguntas: [
          { texto: "Conduta intervencionista urgente?", resposta: "Pericardiocentese (7º EIC citado no material) para aliviar tamponamento; investigar neoplasia vs idiopático vs séptico.", tipo: "dissertativa" },
          { texto: "Neoplasias cardíacas citadas?", resposta: "Hemangiossarcoma atrial direito e linfossarcoma em animais senis.", tipo: "dissertativa" },
        ],
      },
    ],

    topicos: {
      "exame-clinico": "Exame clínico — estrutura e vitais",
      semiotica: "Métodos semióticos",
      "diagnostico-prognostico": "Diagnóstico, tratamento e prognóstico",
      "termos-tecnicos": "Termos técnicos por sistema",
      prescricao: "Prescrição e boas práticas",
      receituario: "Receituário — Portaria 344, SIPEAGRO, MAPA",
      "cardio-peq": "Cardiologia de pequenos animais",
      dmvd: "Degeneração mitral e manejo de ICC",
      hipertensao: "Hipertensão arterial sistêmica",
      "ate-gato": "Tromboembolismo aórtico felino",
      pericardio: "Doenças pericárdicas e neoplasias",
      endocardite: "Endocardite infecciosa",
      respiratorio: "Padrões respiratórios",
      epilepsia: "Convulsões e epilepsia",
    },
  },

  poaTecnologia: {
    id: "poaTecnologia",
    ordem: 30,
    emBreve: true,
    nome: "Tecnologia POA",
    icone: "🔧",
    descricao: "Vai entrando aos poucos — o João atualiza nos próximos dias. Sem pagamento, só calendário.",
    corPrimaria: "#475569",
    corSecundaria: "#94a3b8",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  medicinaVet: {
    id: "medicinaVet",
    ordem: 40,
    emBreve: true,
    nome: "Técnica cirúrgica vet",
    icone: "📘",
    descricao: "Conteúdo futuro no app — em breve.",
    corPrimaria: "#1d4ed8",
    corSecundaria: "#60a5fa",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  inspecaoPOA1: {
    id: "inspecaoPOA1",
    ordem: 50,
    emBreve: true,
    nome: "Inspeção POA-1",
    icone: "📋",
    descricao: "Em breve — matéria será adicionada quando chegar a vez.",
    corPrimaria: "#b45309",
    corSecundaria: "#fbbf24",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  ornitopatologia: {
    id: "ornitopatologia",
    ordem: 60,
    emBreve: true,
    nome: "Ornitopatologia",
    icone: "🐦",
    descricao: "Em breve no calendário de estudos.",
    corPrimaria: "#0e7490",
    corSecundaria: "#22d3ee",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  ginecologiaObstetricia: {
    id: "ginecologiaObstetricia",
    ordem: 70,
    emBreve: true,
    nome: "Ginecologia e obstetrícia animal",
    icone: "🤰",
    descricao: "Em breve — slot reservado para quando for a vez da prova.",
    corPrimaria: "#be185d",
    corSecundaria: "#f472b6",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

  anestesiologiaAnimal: {
    id: "anestesiologiaAnimal",
    ordem: 80,
    emBreve: true,
    nome: "Anestesiologia animal",
    icone: "💉",
    descricao: "Em breve — conteúdo entra com o tempo.",
    corPrimaria: "#6d28d9",
    corSecundaria: "#c4b5fd",
    cramFlashN: 18,
    cramMcN: 12,
    flashcards: [],
    multiplaEscolha: [],
    dissertativas: [],
    casosClinicos: [],
    topicos: {},
  },

};
